#blogs

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTNhZDhhNjFmZGU0ODJhZDRkMWIyOSIsImlhdCI6MTYzNzI0NjYyOCwiZXhwIjoxNjM3MjUwMjI4fQ.GNDvD0AyAitgUKuSpjE4VZkuDzk0d6vAGTYR4Yuht_I

{
   
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5,
    "userId": "6193ad8a61fde482ad4d1b29"
}

###
GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTNhZDhhNjFmZGU0ODJhZDRkMWIyOSIsImlhdCI6MTYzNzI0MjMzMCwiZXhwIjoxNjM3MjQ1OTMwfQ.ZLnuDdMeumLLJ-buiX-W_w6-hWcKzpJ_WMOvJ7Z7x8M

###
GET http://localhost:3003/api/blogs/6193a5c5e844f64a04b1477b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTNhZDhhNjFmZGU0ODJhZDRkMWIyOSIsImlhdCI6MTYzNzI0MjMzMCwiZXhwIjoxNjM3MjQ1OTMwfQ.ZLnuDdMeumLLJ-buiX-W_w6-hWcKzpJ_WMOvJ7Z7x8M

###
DELETE http://localhost:3003/api/blogs/619666f8fd1f3025b82e1cc9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTNhZDhhNjFmZGU0ODJhZDRkMWIyOSIsImlhdCI6MTYzNzI0NjYyOCwiZXhwIjoxNjM3MjUwMjI4fQ.GNDvD0AyAitgUKuSpjE4VZkuDzk0d6vAGTYR4Yuht_I

###
PUT http://localhost:3003/api/blogs/6193a5c5e844f64a04b1477b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxOTNhZDhhNjFmZGU0ODJhZDRkMWIyOSIsImlhdCI6MTYzNzI0MjMzMCwiZXhwIjoxNjM3MjQ1OTMwfQ.ZLnuDdMeumLLJ-buiX-W_w6-hWcKzpJ_WMOvJ7Z7x8M

{
    "author": "Robert C. Martin"
}


# users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "test",
    "name": "Superuser",
    "password": "test"
}

###
GET http://localhost:3003/api/users/


# login

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

